//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Badoo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Badoo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Lang.Badoo", typeof(Badoo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A few extra pounds.
        /// </summary>
        internal static string Body_type_a_few_extra_pounds {
            get {
                return ResourceManager.GetString("Body_type_a_few_extra_pounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athletic.
        /// </summary>
        internal static string Body_type_athletic {
            get {
                return ResourceManager.GetString("Body_type_athletic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string Body_type_average {
            get {
                return ResourceManager.GetString("Body_type_average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muscular.
        /// </summary>
        internal static string Body_type_muscular {
            get {
                return ResourceManager.GetString("Body_type_muscular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t drink.
        /// </summary>
        internal static string Drinking_I_dont_drink {
            get {
                return ResourceManager.GetString("Drinking_I_dont_drink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I drink socially.
        /// </summary>
        internal static string Drinking_I_drink_socially {
            get {
                return ResourceManager.GetString("Drinking_I_drink_socially", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m against drinking.
        /// </summary>
        internal static string Drinking_I_m_against_drinking {
            get {
                return ResourceManager.GetString("Drinking_I_m_against_drinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, never.
        /// </summary>
        internal static string Kids_no_never {
            get {
                return ResourceManager.GetString("Kids_no_never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someday.
        /// </summary>
        internal static string Kids_someday {
            get {
                return ResourceManager.GetString("Kids_someday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By myself.
        /// </summary>
        internal static string Living_by_myself {
            get {
                return ResourceManager.GetString("Living_by_myself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student dormitory.
        /// </summary>
        internal static string Living_student_dormitory {
            get {
                return ResourceManager.GetString("Living_student_dormitory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With parents.
        /// </summary>
        internal static string Living_with_parents {
            get {
                return ResourceManager.GetString("Living_with_parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyiv.
        /// </summary>
        internal static string Location_Kyiv {
            get {
                return ResourceManager.GetString("Location_Kyiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vinnytsia.
        /// </summary>
        internal static string Location_Vinnytsia {
            get {
                return ResourceManager.GetString("Location_Vinnytsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m single.
        /// </summary>
        internal static string Relationship_I_m_single_boy {
            get {
                return ResourceManager.GetString("Relationship_I_m_single_boy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m single.
        /// </summary>
        internal static string Relationship_I_m_single_girl {
            get {
                return ResourceManager.GetString("Relationship_I_m_single_girl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken.
        /// </summary>
        internal static string Relationship_taken {
            get {
                return ResourceManager.GetString("Relationship_taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m straight.
        /// </summary>
        internal static string Sexuality_I_m_straight {
            get {
                return ResourceManager.GetString("Sexuality_I_m_straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t like it.
        /// </summary>
        internal static string Smoking_I_dont_like_it {
            get {
                return ResourceManager.GetString("Smoking_I_dont_like_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hate smoking.
        /// </summary>
        internal static string Smoking_I_hate_smoking {
            get {
                return ResourceManager.GetString("Smoking_I_hate_smoking", resourceCulture);
            }
        }
    }
}
